### ISSUE TITLE
SECURITY: lodash out of date

### ISSUE THREAD

**Issue by loretoparisi** [bda-research/node-webcrawler#11]
```
npm WARN notice [SECURITY] lodash has the following vulnerability: 1 low. Go here for more details: https://nodesecurity.io/advisories?search=lodash&version=3.8.0 - Run `npm i npm@latest -g` to upgrade your npm version, and then `npm audit` to get more info.
```

Please update to latest version.

**Comment by mike442144** [comment]
Hey, pls refer to [crawler](https://github.com/bda-research/node-webcrawler)

**Comment by loretoparisi** [comment]
@mike442144 not sure I understand what you mean. Any action I have to take to help (new issue, other repo)? Thank you!

**Comment by mike442144** [comment]
Oh sorry for that, use  [crawler](https://github.com/bda-research/node-crawler) instead.

**Comment by loretoparisi** [comment]
@mike442144 thank you, replaced!
