### ISSUE TITLE
TypeError: $ is not a function

### ISSUE THREAD

**Issue by mohitathwani** [bda-research/node-webcrawler#4]
I'm trying to execute the sample code and I get the following error:

```
TypeError: $ is not a function
```

What do I need to do to fix this?

**Comment by mike442144** [comment]
@mohitathwani can you detail which sample?

**Comment by mohitathwani** [comment]
I followed the how to install and crash course section in the readme and got the error..

**Comment by tylershuster** [comment]
I'm getting the same issue. On one page with the exact same setup, it correctly passes the $ object, but it another it doesn't. Both return null errors and a complete result object.

**Comment by tylershuster** [comment]
My problem was solved when I removed `utf8=✓` from the link I was crawling.

**Comment by mike442144** [comment]
@mohitathwani @tylershuster I have updated `README`, there are some potential error in callback, one should check if error exists first.
