### ISSUE TITLE
travis build fails

### ISSUE THREAD

**Issue by heshamsafi** [bda-research/node-webcrawler#5]
1) Request tests should crawl a gzip response:
    Uncaught AssertionError: expected false to be true

I have determined that the problem is with the test case.
I will send a pull request with a fix in a few minutes.

**Comment by darrenqc** [comment]
Thank @heshamsafi for helping solve the problem. Please refer to [commit 9ef68cbbdce0f4b8332a3d4470cf47afcb6e1d2f](https://github.com/bda-research/node-webcrawler/commit/9ef68cbbdce0f4b8332a3d4470cf47afcb6e1d2f) for detail.
